// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOy4dK3BhEHfLyGeiNn2B3B_y29fIHAFc',
    appId: '1:535886676306:web:2cbbdad25f196f8f433a8b',
    messagingSenderId: '535886676306',
    projectId: 'earnest-cooler-403412',
    authDomain: 'earnest-cooler-403412.firebaseapp.com',
    storageBucket: 'earnest-cooler-403412.appspot.com',
    measurementId: 'G-GTR4369G5G',
    databaseURL: 'https://earnest-cooler-403412-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwX1KsSA4h5tO0EmXohFC64cNY9N_AbQ0',
    appId: '1:535886676306:android:22ccf322a923e2ee433a8b',
    messagingSenderId: '535886676306',
    projectId: 'earnest-cooler-403412',
    storageBucket: 'earnest-cooler-403412.appspot.com',
    databaseURL: 'https://earnest-cooler-403412-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm82wpuD27KAC4UXihVjSqhXoqWp8qOMQ',
    appId: '1:535886676306:ios:7d6ceb24fa7c1b5c433a8b',
    messagingSenderId: '535886676306',
    projectId: 'earnest-cooler-403412',
    storageBucket: 'earnest-cooler-403412.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
    databaseURL: 'https://earnest-cooler-403412-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm82wpuD27KAC4UXihVjSqhXoqWp8qOMQ',
    appId: '1:535886676306:ios:e9a5dbca55c7ed47433a8b',
    messagingSenderId: '535886676306',
    projectId: 'earnest-cooler-403412',
    storageBucket: 'earnest-cooler-403412.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebase.RunnerTests',
    databaseURL: 'https://earnest-cooler-403412-default-rtdb.firebaseio.com/',
  );
}
